[project]
name = "sync-ecdsa-verifier"
authors = ["Sync Security Team"]
description = "Decentralized ECDSA signature verification system"
telemetry = false
requirements = []
[contracts.governance]
path = "contracts/governance.clar"
depends_on = []

[contracts.verification-protocol]
path = "contracts/verification-protocol.clar"
depends_on = []

[contracts.signature-registry]
path = "contracts/signature-registry.clar"
depends_on = []

[contracts.challenge-response]
path = "contracts/challenge-response.clar"
depends_on = []

[contracts.rewards-distribution]
path = "contracts/rewards-distribution.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
